name: Python CI + Docker Deploy to Render (sem uses)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar reposit贸rio manualmente
        run: |
          git clone https://github.com/${{ github.repository }} .
          echo "C贸digo clonado."

      - name: Build Docker image
        run: docker build -t desafiodevops:latest .

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Baixar reposit贸rio manualmente
        run: |
          git clone https://github.com/${{ github.repository }} .
          echo "C贸digo clonado."

      - name: Build Docker image para testes
        run: docker build -t desafiodevops:test .

      - name: Executar testes dentro do Docker
        run: docker run --rm desafiodevops:test python -m unittest discover

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Disparar Deploy (Render ou outro)
        run: curl -X POST ${{ secrets.BALEIA }}
