name: Python CI + Docker Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # - name: Verificar existência do Dockerfile 
      #   run: test -f Dockerfile

      - name: Build Docker image
        run: docker build -t desafiodevops:latest .
      
      # - name: Setup do Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'
      
      # - name: Install dependencies
      #   run: pip install -r requirements.txt


  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Setup do Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'

      - name: Build Docker image 
        run: docker build -t desafiodevops:test . 

      - name: Run tests inside Docker
        run: docker run --rm desafiodevops:test python -m unittest discover
      
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      
      - name: Trigger Baleia
        run: curl -X POST ${{ secrets.BALEIA }}
